# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import restaurant_pb2 as restaurant__pb2


class servicioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reservar = channel.unary_unary(
                '/servicio.servicio/reservar',
                request_serializer=restaurant__pb2.ReservationRequest.SerializeToString,
                response_deserializer=restaurant__pb2.Response.FromString,
                )
        self.comprobar = channel.unary_unary(
                '/servicio.servicio/comprobar',
                request_serializer=restaurant__pb2.Request.SerializeToString,
                response_deserializer=restaurant__pb2.Response.FromString,
                )
        self.cancelar = channel.unary_unary(
                '/servicio.servicio/cancelar',
                request_serializer=restaurant__pb2.Request.SerializeToString,
                response_deserializer=restaurant__pb2.Response.FromString,
                )
        self.listar = channel.unary_unary(
                '/servicio.servicio/listar',
                request_serializer=restaurant__pb2.ListRequest.SerializeToString,
                response_deserializer=restaurant__pb2.Response.FromString,
                )


class servicioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reservar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def comprobar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cancelar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_servicioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reservar': grpc.unary_unary_rpc_method_handler(
                    servicer.reservar,
                    request_deserializer=restaurant__pb2.ReservationRequest.FromString,
                    response_serializer=restaurant__pb2.Response.SerializeToString,
            ),
            'comprobar': grpc.unary_unary_rpc_method_handler(
                    servicer.comprobar,
                    request_deserializer=restaurant__pb2.Request.FromString,
                    response_serializer=restaurant__pb2.Response.SerializeToString,
            ),
            'cancelar': grpc.unary_unary_rpc_method_handler(
                    servicer.cancelar,
                    request_deserializer=restaurant__pb2.Request.FromString,
                    response_serializer=restaurant__pb2.Response.SerializeToString,
            ),
            'listar': grpc.unary_unary_rpc_method_handler(
                    servicer.listar,
                    request_deserializer=restaurant__pb2.ListRequest.FromString,
                    response_serializer=restaurant__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'servicio.servicio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class servicio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reservar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/servicio.servicio/reservar',
            restaurant__pb2.ReservationRequest.SerializeToString,
            restaurant__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def comprobar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/servicio.servicio/comprobar',
            restaurant__pb2.Request.SerializeToString,
            restaurant__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def cancelar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/servicio.servicio/cancelar',
            restaurant__pb2.Request.SerializeToString,
            restaurant__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/servicio.servicio/listar',
            restaurant__pb2.ListRequest.SerializeToString,
            restaurant__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
